set -e
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-hammer /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/corrected/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/compress_all.py --input_file /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/corrected/corrected.yaml --ext_python_modules_home /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades --max_threads 16 --output_dir /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/corrected --not_used_yaml_file /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/corrected/dont_correct.yaml --gzip_output
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/copy_files.py /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/before_rr.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/before_rr.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/assembly_graph_after_simplification.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/assembly_graph_after_simplification.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/final_contigs.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/contigs.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/first_pe_contigs.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/first_pe_contigs.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/strain_graph.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/strain_graph.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/scaffolds.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/scaffolds.fasta /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/scaffolds.paths /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/scaffolds.paths /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/assembly_graph_with_scaffolds.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/assembly_graph_with_scaffolds.gfa /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/assembly_graph.fastg /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/assembly_graph.fastg /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/K55/final_contigs.paths /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/contigs.paths
true
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/scaffolds.fasta --misc_dir /gorilla/home/zhanj/Genome-Analysis/analyses/02_genome_assembly/spades_Efaecium/misc --threshold_for_breaking_scaffolds 3
true
